version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports: ["5000:5000"]
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GITLAB_PRIVATE_TOKEN: ${GITLAB_PRIVATE_TOKEN}
      GITLAB_API_URL: https://gitlab.cs.ttu.ee/api/v4

  frontend:
    build:
      context: ./frontend
      args:
        NPM_USER: ${NPM_USER}
        NPM_PASS: ${NPM_PASS}
    restart: always
    depends_on: [backend]

  caddy:
    image: caddy:2-alpine
    restart: always
    depends_on: [frontend, backend]
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro